version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - ./www:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      - mysql
      - memcached
    networks:
      - bitrix-net

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - bitrix-net

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql-mode=""
      --transaction-isolation=READ-COMMITTED
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
      --innodb_flush_log_at_trx_commit=2
      --innodb_strict_mode=0
    networks:
      - bitrix-net

  memcached:
    image: memcached:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_memcached
    restart: always
    networks:
      - bitrix-net

networks:
  bitrix-net:
    driver: bridge

volumes:
  db_data: