version: '3.8'

services:
  php:
    build: ./docker/php
    volumes:
      - ./www:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    environment:
      XDEBUG_CONFIG: client_host=host.docker.internal
    depends_on:
      - mysql
      - memcached
      - redis
    networks:
      - bitrix-net

  nginx:
    image: nginx:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - bitrix-net

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --sql-mode=""
      --transaction-isolation=READ-COMMITTED
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
      --innodb_flush_log_at_trx_commit=2
      --innodb_strict_mode=0
    networks:
      - bitrix-net

  memcached:
    image: memcached:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_memcached
    restart: always
    networks:
      - bitrix-net

  redis:
    image: redis:alpine
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    restart: always
    command: redis-server --appendonly no --save ""
    volumes:
      - redis_data:/data
    networks:
      - bitrix-net

  node:
    image: node:25-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_node
    volumes:
      - ./www:/var/www/html
    working_dir: /var/www/html/local/js
    command: tail -f /dev/null
    user: "1000:1000"
    ports:
      - "5173:5173"
    networks:
      - bitrix-net

  mysql-exporter:
    image: prom/mysqld-exporter:v0.18.0
    container_name: ${COMPOSE_PROJECT_NAME}_mysql_exporter
    volumes:
      - ./docker/mysql-exporter/.my.cnf:/home/.my.cnf:ro
    command:
      - '--config.my-cnf=/home/.my.cnf'
      - '--collect.info_schema.innodb_metrics'
      - '--collect.info_schema.processlist'
      - '--collect.info_schema.tables'
      - '--collect.slave_status'
    depends_on:
      - mysql
    networks:
      - bitrix-net
    restart: always

  redis-exporter:
    image: oliver006/redis_exporter
    environment:
      REDIS_ADDR: "redis:6379"
    depends_on:
      - redis
    networks:
      - bitrix-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: ${COMPOSE_PROJECT_NAME}_cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: always
    networks:
      - bitrix-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: ${COMPOSE_PROJECT_NAME}_node_exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+)($$|/)'
    networks:
      - bitrix-net
    restart: always

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - bitrix-net

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
    depends_on:
      - prometheus
    networks:
      - bitrix-net

  loki:
    image: grafana/loki:3.3.0
    container_name: ${COMPOSE_PROJECT_NAME}_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - bitrix-net

  promtail:
    image: grafana/promtail:3.3.0
    container_name: ${COMPOSE_PROJECT_NAME}_promtail
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    ports:
      - "9080:9080"
    depends_on:
      - loki
    networks:
      - bitrix-net

networks:
  bitrix-net:
    driver: bridge

volumes:
  db_data:
  redis_data:
  prometheus_data:
  grafana_data: